### ISSUE TITLE
twiperf -u -c: Ctrl-C can't kill it.

### ISSUE THREAD

**Issue by wenjing** [twister2016/twister#64]
Ctrl-C works for twiperf -s.
But doesnt work for twiperf -c. I will only exit after a long timeout.

**Comment by wriaz** [comment]
It only happens when client transmits traffic at rates higher than its line capacity. Issue disappears by adding the bandwidth flag `-b` to limit the packet rate below client's line rate. 
Fix added in following commit.
https://github.com/twister2016/twister/commit/185fef75f32982ea3648d7d6aa7c9a72895c323a
